@component('mail::message')
New Tickets has been generated by {{$clientName}}
Tap on the link below to check the ticket

@component('mail::button', ['url' => config('app.front_end_base_url').'/reset-password/'.$random_token, 'color' => 'success'])
Check The Ticket
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent